POST http://localhost:3000/auth
Content-Type: application/json

{
    "email":"stephanbazaar@gmail.com",
    "password":"123456"
}

###
POST http://localhost:3000/create
Content-Type: application/json

{
    "username":"darkcoder",
    "email":"stephanbazaar99@gmail.com",
    "password":"admin"
}